spring:
  application:
    name: chef-mgmt-mail
  artemis:
    broker-url: tcp://localhost:61616
    mode: native
  datasource:
    url: jdbc:postgresql://localhost:5432/chef_mgmt_db
    username: postgres
    password: postgres
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
server:
  port: 8888
  servlet:
    context-path: '/api'
queues:
  mail-request-queue: mail-request-queue