spring:
  application:
    name: chef-mgmt-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/chef_mgmt_db
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
      - classpath:db/data
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8777
  servlet:
    context-path: '/api'
